Add calculation logic
Rim-777/ElixirCourseHomeWork-1 pull request #1
Opened 2024-02-15 18:17 UTC by Rim-777

2024-02-18 05:51 UTC, am-kantox approved these changes
All good, but when one returns `{:ok, 0}` from `init/1` callback, I expect the state to be used later (which is not the case.)

2024-02-18 05:51 UTC, am-kantox commented on lib/calculator.ex
> +  end
Once we already have a `GenServer`, which means we are stateful, I’d also keep the current value in the state _and_ implement `call/2`, taking the second argument from the state to make it chainable, like 
```elixir
Calculator.call(:add, 3, 5)
#⇒ 8
Calculator.call(:add, 3)
#⇒ 11
```

```

2024-02-18 05:51 UTC, am-kantox commented on lib/calculator.ex
> +  def handle_call({:divide, num_1, num_2}, _from, state) do
`Calculator.call(:divide, 5, 0)` would raise, which is probably not expected.

2024-02-18 15:13 UTC, am-kantox requested changes
I nevertheless accepted it already, but let’s polish it to a shine.

2024-02-18 15:13 UTC, am-kantox commented on test/calculator_test.exs
> +  test ~c"calculates numbers" do
Eh? One does not need a charlist here, `String.t()` works.
```suggestion
  test "calculates numbers" do
```

2024-02-18 15:13 UTC, am-kantox commented on lib/calculator.ex
> +    unproccessable_operation(state)
Now this code behaves differently on different kinds of bad arguments. When `0` is passed as a second argument to `:divide`, it gracefully returns an error. When a string or some other garbage is passed, it crashes.

I’d go with any solution, but not with both simultaneously.

Basically, you might even not leak the wrong input to the process. Use guards in the interface calls (see the comment there.)

2024-02-18 15:13 UTC, am-kantox commented on lib/calculator.ex
> +  end
Showing guards here only (see the comment below.) `call/2` would be the same.

```suggestion
  def call(:divide, _num_1, 0) do
    :go_learn_arithmetics
  end
  def call(operation, num_1, num_2) when is_number(num_1) and is_number(num_2) do
    GenServer.call(__MODULE__, {operation, num_1, num_2})
  end
  def call(operation, _num_1, _num_2) do
        :go_learn_arithmetics
  end
```

2024-02-18 15:13 UTC, am-kantox commented on lib/calculator.ex
> +    {:reply, new_satate, new_satate}
Summoning **Satate** from _Elixir_ code is prohibited by law.

2024-02-18 15:13 UTC, am-kantox commented on test/calculator_test.exs
> +    assert Calculator.call(:add, 7) == 7
I miss tests for wrong input data.

2024-02-19 13:03 UTC, Rim-777 commented on lib/calculator.ex
> +    {:reply, new_satate, new_satate}
здесь я, к сожалению,  не совсем понял, о чем именно идет речь

2024-02-19 15:47 UTC, am-kantox commented
:tada:

2024-02-19 15:56 UTC, Rim-777 commented on lib/calculator.ex
> +    {:reply, new_satate, new_satate}
I realized that it was a typo, that was not what was unclear.
I didn't get the expression in general, I'm sorry.
 Which line is incorrect?

2024-02-19 16:35 UTC, am-kantox commented on lib/calculator.ex
> +    {:reply, new_satate, new_satate}
Lines are fine, I just wanted to see `state` everywhere instead of `satate` and I probably made a bad dad joke about `satate` sounds much like `Satan`.

Nevermind :)

2024-02-19 18:01 UTC, Rim-777 commented on lib/calculator.ex
> +    {:reply, new_satate, new_satate}
> state
Ah, OMG, I missed that you pointed to my typo, and thought that you tried to explain something that matters and is obvious but by chance made a typo 😂 OK, thanks a lot,  I have to probably get used to your humor

2024-02-20 12:37 UTC, am-kantox commented
> Sorry for disturbing you again (…)

Don’t sorry me, please, in such a case. I signed the contract to be disturbed day and night by code questions. 

Sky’s the limit to code improvements, but this already looks robust enough.

2024-02-20 12:38 UTC, am-kantox approved these changes

2024-02-20 13:41 UTC, merged